### ISSUE TITLE
"Error: Frida server did not start" with fresh jailbreak on iPhone

### ISSUE THREAD

**Issue by mal-tee** [tweaselORG/cli#24]

**Comment by zner0L** [comment]
Well, it seems like frida is not installed correctly on the devices. Apparently, frida changed something about their apt repository, because now I get a 404, if I run `apt --allow-unauthenticated install re.frida.server`:
```
Err:1 https://build.frida.re ./ re.frida.server 16.1.0
  404  Not Found [IP: 2a06:98c1:3120::3 443]
E: Failed to fetch https://build.frida.re/pool/main/r/re.frida.server/re.frida.s
erver_16.1.0_iphoneos-arm.deb  404  Not Found [IP: 2a06:98c1:3120::3 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-mis
sing?
```

**Comment by zner0L** [comment]
Interesting. I tried to install frida 16.1.0, forwhich there is no version available. But for frida 16.1.1 there is. I ran `apt search frida` and now suddenly, it chooses the right version and installs correctly.

**Comment by zner0L** [comment]
I guess that is a caching problem? Though I am unsure what is going wrong here. I’ll try to delete `/var/lib/apt/lists/*`, so I can be sure to get fresh sources in `apt --allow-insecure-repositories update`.
