### ISSUE TITLE
Generate "protocol" log with version info, etc. for report validation

### ISSUE THREAD

**Issue by mal-tee** [tweaselORG/cli#25]
- tweasel version
- version and hash of subject
- etc.

**Comment by baltpeter** [comment]
This is pretty much what I'm doing in https://github.com/tweaselORG/cyanoacrylate/issues/39. And since cyanoacrylate write the metadata into the HAR file, we'll get the functionality here "for free" after we upgrade.

See https://github.com/tweaselORG/cli/issues/34 for displaying the information.
