### ISSUE TITLE
`record-traffic` fails

### ISSUE THREAD

**Issue by mal-tee** [tweaselORG/cli#39]
```
tweasel record-traffic com.enchantedcloud.photovault-625.apk     
    TypeError: Module "file:///home/malte/.config/yarn/global/node_modules/appstraction/package.json" needs an import assertion of type "json"
    Code: ERR_IMPORT_ASSERTION_TYPE_MISSING
```

**Comment by mal-tee** [comment]
related to https://github.com/tweaselORG/cyanoacrylate/issues/50

**Comment by baltpeter** [comment]
Thanks! This looks like the same problem as https://github.com/tweaselORG/cli/issues/38, which should be fixed through the hotfix in https://github.com/tweaselORG/cli/releases/tag/v1.0.2. Let me know in case the problem still occurs with the new version.
