### ISSUE TITLE
"Setting up": Show progress or display ETA

### ISSUE THREAD

**Issue by mal-tee** [tweaselORG/cli#8]

**Comment by baltpeter** [comment]
This is definitely a fair request. I'm really not sure what a good way of displaying a progress bar would be, but we could at the very least be more granular in our output.

Listr does support nested tasks, so we could display which sub-step we're currently on without much effort. That should hopefully give a better indication as to what's actually happening and additionally make it easier to debug if something goes wrong.

**Comment by baltpeter** [comment]
It should now be a lot more obvious that we're waiting for the device to be connected:

![image](https://github.com/tweaselORG/cli/assets/4048809/d0211d28-80e6-4f78-b6ec-8211798dff70)
